% In the paper they use the average error and the standard deviation of
% some properties of the landscape generated by the algorithm which I
% cannot use since in AMIGO I cannot precicesly determine the peack density
% ratio, the ratio of local optima or valley structure coeficient. Once I
% start getting results I will see if there is some characteristics that
% can be used. Nevertheless, I can generate radar plots for different
% performance measures of an algorithm trying to minimize or maximize the
% area of the plot since it is quite visual and helpfull to have an insigth
% or idea of the total of measurements done. 
% Matlab has no radar plot by itself, fut there are different functions in
% the Ad-on window. Form all the ones tested the easiest and more visual
% (most of them give spider plots that are not that intuitive to interpret)
% is the function radarplot(X, label, color) which works with columns, not
% rows. radarplot([1 ; 2; 0 ; 3; 2 ],{ 'a' ; 'b' ; 'c' ; 'd' ; 'e' } ,'r')
% I have to save all the figures manually, aparentlly if you asign the plot
% to a variable so it can be saved it gives error (not possible to assign)
% and introducing the entire expresion in the saveas first argument gives
% the same error as well. 

function [] = RadarPlots (label, PerformanceMeasuresMatrix, LabelsMatrix, color)

radarplot(PerformanceMeasuresMatrix,LabelsMatrix ,color);
title(label)

end